/*
 * main.c
 * Author: Loredana Sandu
 * Description: Classifies 2-dimensional or 3-dimensional cones.
 */

#include <string.h>
#include "vector-operations.h"
#include "classification-functions.h"

int main()
{
    /* Open the input file in reading mode */

    char name_file[100];
    char path_file[200];
    printf("\nName of the input file, found in the in_file directory, including extension and with no spaces: ");
    scanf("%s", name_file);

    sprintf(path_file,"../in_files/%s",name_file);

    FILE * file = fopen(path_file, "r");
    if (file == NULL){
        printf("\nError: Couldn't open input file.\n");
        return 1;
    }


    /* Count lines of input file, that is, the number of given vectors. */

    unsigned int n = 1, i, j;
    char character;
    do {
        character = fgetc(file);
        if (character == '\n' && fgetc(file) != '\n' && fgetc(file) != EOF){
            n++;
        }
    } while (character != EOF);


    /* Read given vectors of input file, checking they aren't null. */

    rewind(file);
    double * generators_v[n];       // Array of pointers to generating vectors v_i.
    for (i=0; i<n; i++){
        generators_v[i] = malloc(LEN * sizeof(double));
        if (generators_v[i] == NULL){
            printf("\nError: couldn't reserve memory for vector v_%d\n", i+1);
            return 1;
        }
    }

    unsigned int vector_is_null;    // Variable with boolean values to check that every v_i is not null.

    for (i=0; i<n; i++){
        vector_is_null = 1;
        fscanf(file, "%lf,%lf,%lf\n", &generators_v[i][0], &generators_v[i][1], &generators_v[i][2]);
        for (j=0; j<LEN; j++){
            if (generators_v[i][j] != 0){
                vector_is_null = 0;
            }
        }
        if (vector_is_null == 1){
        printf("\nError: no generator v_i can be null.\n");
        return 1;
        }
    }


    /* Classify cone and compute the set of minimal generating vectors. n*/

    unsigned int vectors_min[n];        // Will contain the indexes of the v_i that form the set of minimal generators, with initial length 0.
    unsigned int len_vectors_min = 0;

    unsigned int classification = classification3d(n, generators_v, vectors_min, &len_vectors_min);

    printf("\nRead a cone generated by %u given vectors.\n", n);

    switch (classification){
    case 0:
        printf("The cone is {0}.\n");
        break;
    case 1:
        printf("The cone is a ray.\n");
        break;
    case 2:
        printf("The cone is a line.\n");
        break;
    case 3:
        printf("The cone is a plane angle.\n");
        break;
    case 4:
        printf("The cone is a half-plane.\n");
        break;
    case 5:
        printf("The cone is a plane.\n");
        break;
    case 6:
        printf("It is a polyhedral cone with %d edges.\n", len_vectors_min);
        break;
    case 7:
        printf("The cone is a solid dihedral angle.\n");
        break;
    case 8:
        printf("The cone is a half-space.\n");
        break;
    case 9:
        printf("The cone is the space.\n");
        break;
    default:
        printf("Error: couldn't classify the cone.\n");
    }


    if (classification == 0){
        printf("It doesn't have a set of minimal generating vectors.\n");
    } else {
        printf("A set of minimal generating vectors is {");
        for (i=0; i<len_vectors_min; i++){
            printf("v_%d, ", vectors_min[i] + 1);
        }
        printf("\b\b}\n\n");
    }


    /* Open the output file in writing mode */

    char name_output_file[100];
    char path_output_file[200];
    printf("\nName of the output file, located in the out_file directory, where the minimal generating vectors will be written: ");
    scanf("%s", name_output_file);

    sprintf(path_output_file,"../out_files/%s",name_file);

    FILE * output_file = fopen(path_output_file, "w");
    if (output_file == NULL){
        printf("\nError: Couldn't open output file.\n");
        return 1;
    }


    /* Escriptura dels vectors generadors minimals en el fitxer sortida */

    for (i=0; i<len_vectors_min; i++){
        for (j=0; j<LEN; j++){
            if (j != LEN - 1){
                fprintf(output_file, "%f,\t", generators_v[vectors_min[i]][j]);
            } else {
                fprintf(output_file, "%f\n", generators_v[vectors_min[i]][j]);
            }
        }
    }

    fclose(file);
    fclose(output_file);

    for (i=0; i<n; i++){
        free(generators_v[i]);
    }

    return 0;
}